const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765');await page.locator('[data-field=name]').waitFor();
  const field=k=>page.locator(`[data-field="${k}"]`);
  await field('health').fill('17');await page.locator('#new-character-button').click();
  assert.ok(await page.locator('#leave-dialog').evaluate(e=>e.open));
  await page.locator('#stay').click();assert.equal(await field('health').inputValue(),'17');
  await page.locator('#new-character-button').click();await page.locator('#discard').click();
  await page.locator('#cancel-new-character').click();assert.equal(await field('health').inputValue(),'');
  assert.equal(await page.locator('.cast-row').count(),18);
  await page.locator('[data-event="6"]').click();
  await page.locator('#cast-search').fill('Mira');
  await page.locator('#new-character-button').click();
  await page.locator('#new-character-name').fill('   ');await page.locator('#new-character-form button[type=submit]').click();
  assert.ok(await page.locator('#new-character-dialog').evaluate(e=>e.open));
  await page.locator('#new-character-name').fill('  Rowan Test  ');
  await page.locator('#new-character-summary').fill('A cartographer searching for a lost road.');
  await page.screenshot({path:path.join(__dirname,'new-character-dialog.png')});
  await page.locator('#new-character-form button[type=submit]').click();
  assert.equal(await field('name').inputValue(),'Rowan Test');assert.equal(await page.locator('#event-position').textContent(),'7 / 10');
  assert.equal(await page.locator('.cast-row').count(),19);assert.equal(await page.locator('#cast-search').inputValue(),'');
  assert.equal(await page.locator('#review-button').isDisabled(),true);
  assert.equal(await field('summary').inputValue(),'A cartographer searching for a lost road.');
  await page.screenshot({path:path.join(__dirname,'new-character-profile.png')});
  await page.locator('[data-event="0"]').click();assert.equal(await field('name').inputValue(),'Rowan Test');
  await page.locator('[data-add-connection]').click();await page.locator('#connection-person').selectOption({label:'Mira Vale'});
  await page.locator('#connection-form button[type=submit]').click();
  await field('species').fill('Half-elf');await page.locator('#bottom-review-button').click();await page.locator('#review-form button[type=submit]').click();
  await page.reload();await field('name').waitFor();assert.equal(await page.locator('.cast-row').count(),19);
  await page.locator('.cast-row').filter({hasText:'Rowan Test'}).click();assert.equal(await field('species').inputValue(),'Half-elf');
  assert.equal(await page.locator('.connection-person').filter({hasText:'Mira Vale'}).count(),1);
  await page.locator('.connection-person').filter({hasText:'Mira Vale'}).click();assert.equal(await page.locator('.connection-person').filter({hasText:'Rowan Test'}).count(),1);
  await page.setViewportSize({width:390,height:844});await page.locator('#new-character-button').click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.keyboard.press('Escape');
  await page.locator('#about-button').click();await page.locator('#reset-button').click();await page.locator('#confirm-reset').click();
  assert.equal(await page.locator('.cast-row').count(),18);
  await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new Error('Storage unavailable');};});
  await page.locator('#new-character-button').click();await page.locator('#new-character-name').fill('Session character');
  await page.locator('#new-character-form button[type=submit]').click();assert.equal(await field('name').inputValue(),'Session character');
  assert.match(await page.locator('#save-state').textContent(),/Session only/);
  assert.deepEqual(errors,[]);
  console.log('PASS: dirty guard; cancel; whitespace validation; immediate profile; search reset; all-event availability; historical connection; reload; saved profile edits; mobile; reset; storage failure.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
