const categories=[['species','Races & species','The peoples who inhabit your world.'],['role','Roles','Occupations and callings for your cast.'],['faction','Factions','The groups your characters belong to.'],['location','Locations','Places that give your story a home.'],['language','Languages','Spoken, written, and forgotten languages.'],['belief','Religions & beliefs','Faiths, traditions, and guiding ideas.'],['title','Titles & ranks','Honors and positions in your world.']];
export function createWorldView({root,esc,options,description,save}){
  let category='species',query='';
  const dialog=document.createElement('dialog');dialog.id='world-entry-dialog';dialog.setAttribute('aria-labelledby','world-entry-title');document.body.append(dialog);
  function edit(name=''){
    const label=categories.find(c=>c[0]===category)[1];
    dialog.innerHTML=`<form id="world-entry-form"><div class="dialog-header"><span class="eyebrow">${esc(label)}</span><h2 id="world-entry-title">${name?'Entry details':'Add entry'}</h2><p>Shared throughout the story.</p></div><div class="connection-form-fields"><label class="field">Name<input id="world-entry-name" required maxlength="120" ${name?'readonly':''} value="${esc(name)}" autocomplete="off"></label><label class="field">Description <span class="muted">Optional</span><textarea id="world-entry-description" rows="4">${esc(description(category,name))}</textarea></label>${name?'<p class="muted">The name stays consistent with existing character assignments.</p>':''}</div><div class="dialog-actions"><button type="button" class="secondary" id="world-entry-cancel">Cancel</button><button class="primary" type="submit">Save entry</button></div></form>`;
    dialog.querySelector('#world-entry-cancel').onclick=()=>dialog.close();
    const input=dialog.querySelector('input');input.oninput=()=>input.setCustomValidity('');
    dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const value=input.value.trim();if(!value){input.setCustomValidity('Enter a name.');input.reportValidity();return;}if(!name&&options(category).some(n=>n.toLowerCase()===value.toLowerCase())){input.setCustomValidity('This entry already exists. Open it to add a description.');input.reportValidity();return;}save(category,value,dialog.querySelector('textarea').value.trim());dialog.close();query='';render();};
    dialog.showModal();dialog.querySelector(name?'textarea':'input').focus();
  }
  function entries(){const list=options(category).filter(n=>`${n} ${description(category,n)}`.toLowerCase().includes(query.toLowerCase()));root.querySelector('.world-entries').innerHTML=list.map(n=>`<button class="world-entry" data-world-entry="${esc(n)}"><strong>${esc(n)}</strong><span>${esc(description(category,n))||'Add a description…'}</span><span aria-hidden="true">↗</span></button>`).join('')||'<p class="world-empty">'+(query?'No entries match your search.':'No entries yet. Add the first one to start your reference list.')+'</p>';root.querySelectorAll('[data-world-entry]').forEach(b=>b.onclick=()=>edit(b.dataset.worldEntry));}
  function render(){const [,label,hint]=categories.find(c=>c[0]===category);root.innerHTML=`<div class="world-heading"><span class="eyebrow">YOUR STORY’S FOUNDATIONS</span><h1>World of Greyhaven</h1><p>Define it once. Bring it into every character’s story.</p></div><div class="world-library"><nav class="world-categories" aria-label="World reference lists">${categories.map(([key,title])=>`<button data-world-category="${key}" aria-current="${key===category?'true':'false'}"><span>${title}</span><span class="count">${options(key).length}</span></button>`).join('')}</nav><section class="world-list"><div class="world-list-heading"><div><h2>${label}</h2><p>${hint}</p></div><button class="primary" id="world-add">+ Add entry</button></div><p class="world-assignment">${['species','role','faction','location'].includes(category)?'Available in character profile dropdowns at every event.':'A shared reference list. Character assignment will come later.'}</p><input id="world-search" type="search" aria-label="Search world entries" placeholder="Find an entry…" value="${esc(query)}"><div class="world-entries"></div></section></div><section class="world-reserved" aria-label="Future world features"><div class="world-map-placeholder"><span class="eyebrow">WORLD MAP · PLANNED</span><h2>A place for every journey</h2><p>A map image with named location pins will live here.</p></div><div class="world-writing-placeholder">${['World summary','Lore',"Author’s notes"].map(n=>`<div><h2>${n}</h2><span class="muted">Reserved for a future step</span></div>`).join('')}</div></section>`;root.querySelectorAll('[data-world-category]').forEach(b=>b.onclick=()=>{category=b.dataset.worldCategory;query='';render();});root.querySelector('#world-add').onclick=()=>edit();root.querySelector('#world-search').oninput=e=>{query=e.target.value;entries();};entries();}
  return {render};
}
