"""The expanded Greyhaven cast, chapter outline, and supporting connections.

Short names are stable sample-data keys, never identifiers in user stories.
"""

def profile(name, role, faction, location, summary, backstory, motivation, traits, skills, inventory):
    return dict(name=name, role=role, species='Human', faction=faction, location=location,
                status='Active', summary=summary, backstory=backstory,
                notes=f'Motivation: {motivation}', traits=traits, skills=skills,
                inventory=inventory, tags=faction)


EXTRA_CAST = (
    profile('Nessa Reed', 'Ferryman', 'Riverfolk', 'Old Quay',
            'Elias’s daughter can cross the river without being seen.',
            'Inherited a failing ferry and refused to sell its landing to Ash Trading.',
            'Find her father without sacrificing her neighbors to the Watch.',
            'Stubborn, resourceful', 'Navigation, rowing, concealment', 'Ferry keys, river charts, signal whistle'),
    profile('Rowan Vale', 'Dock clerk', 'Dockworkers', 'South Warehouse',
            'Mira’s brother is hiding after copying a dangerous cargo ledger.',
            'Signed false manifests to pay family debts, then found poisoned medicine among the cargo.',
            'Give Mira the original ledger and admit his own part in the fraud.',
            'Ashamed, observant', 'Bookkeeping, forgery detection', 'Ledger pages, warehouse seal'),
    profile('Iona Bell', 'Newspaper editor', 'Free Press', 'Bell Printworks',
            'An editor risks her press to publish the shipment evidence.',
            'A retracted story once ruined an innocent sailor; she now demands independent sources.',
            'Publish proof rather than another rumor.',
            'Exacting, brave', 'Interviewing, printing, research', 'Type blocks, reporter notebook'),
    profile('Garrick Voss', 'Customs magistrate', 'City Council', 'Customs House',
            'The magistrate protects a smuggling scheme behind legal paperwork.',
            'Turned emergency harbor powers into a private toll on imported medicine.',
            'Destroy the original ledger before the public hearing.',
            'Patient, vindictive', 'Law, coercion, accounting', 'Warrant book, silver seal'),
    profile('Bram Holt', 'Union organizer', 'Dockworkers', 'South Warehouse',
            'A dockworker organizes a strike as the sickness spreads.',
            'Lost a crew member to a sealed shipment and no longer trusts official inspections.',
            'Win safe working conditions without starving the docks.',
            'Protective, impatient', 'Organizing, lifting, negotiation', 'Union roll, crowbar'),
    profile('Sable Quinn', 'Smuggler captain', 'Riverfolk', 'Floodgate Inn',
            'A smuggler offers a route beneath the customs blockade.',
            'Once carried Ash cargo, then discovered the concealed patients aboard a transport.',
            'Keep her crew free and repay the families she unknowingly harmed.',
            'Wry, cautious', 'Sailing, disguise, bargaining', 'Boat deed, false flags'),
    profile('Oren Flint', 'Clockmaker', 'Lantern Guild', 'Clocktower',
            'Pip’s former teacher can repair the city’s flood alarm.',
            'His mechanisms were copied to build locks for an illegal quarantine ward.',
            'Break those locks and restore the warning bells.',
            'Gentle, methodical', 'Engineering, locksmithing', 'Precision tools, clock plans'),
    profile('Liora Fen', 'Ward physician', 'Mercy House', 'Mercy Ward',
            'A physician traces the sickness to diluted antidotes.',
            'Treated the first cases quietly because officials threatened to close her ward.',
            'Obtain clean medicine and protect her patient records.',
            'Compassionate, exhausted', 'Diagnosis, surgery, chemistry', 'Case files, medical bag'),
    profile('Tamsin Crow', 'Watch lieutenant', 'Harbor Watch', 'North Gate',
            'Thorne’s lieutenant must choose between a warrant and her conscience.',
            'Rose through the Watch after exposing payroll theft and believes procedure can still work.',
            'Make the arrests stand up in court.',
            'Precise, skeptical', 'Investigation, archery, evidence handling', 'Evidence satchel, bow'),
    profile('Corin Ash', 'Shipping heir', 'Ash Trading Company', 'Merchant Quarter',
            'Seraphine’s younger brother handles the company’s quiet charity shipments.',
            'Borrowed Voss’s money to keep Mercy House supplied without reading its conditions.',
            'Protect patients and his sister without covering up the fraud.',
            'Idealistic, evasive', 'Logistics, diplomacy', 'Charity manifests, family signet'),
    profile('Ada Moss', 'Innkeeper', 'Riverfolk', 'Floodgate Inn',
            'The innkeeper shelters witnesses behind a busy common room.',
            'Kept the inn open through two floods and knows which tunnels remain passable.',
            'Keep refugees safe until they can testify.',
            'Warm, unyielding', 'Cooking, mediation, local history', 'Cellar keys, guest ledger'),
    profile('Dorian Pike', 'Council speaker', 'City Council', 'Council Hall',
            'A cautious speaker controls whether the evidence reaches a public hearing.',
            'Won office on harbor prosperity and fears a scandal will destroy the city’s credit.',
            'Save the council’s legitimacy by allowing an honest inquiry.',
            'Diplomatic, anxious', 'Oratory, procedure', 'Council charter, meeting docket'),
    profile('Wren Sol', 'Lighthouse keeper', 'Lantern Guild', 'West Lighthouse',
            'A keeper tracks night signals exchanged with unregistered ships.',
            'Inherited the post from a parent dismissed for reporting the same signal pattern.',
            'Clear the family name and guide rescuers through the storm.',
            'Solitary, loyal', 'Signal codes, weather reading, climbing', 'Signal log, telescope, climbing rope'),
)

# Order, title, summary, and participant keys. The first five keys belong to the
# original sample and are kept so older tutorials still make sense.
EVENTS = (
    (1, 'The dockside fever', 'Mira and Liora discover that workers receiving the same imported tonic are becoming ill. Bram demands an inspection; Rowan disappears with a manifest.', 'mira liora bram rowan'),
    (2, 'A fragile pact', 'Seraphine funds Mira’s inquiry to protect her company. Pip carries the agreement while Corin opens the charity shipment records.', 'mira seraphine pip corin'),
    (3, 'The missing archivist', 'Elias recognizes a counterfeit customs seal and vanishes. Nessa and Thorne search the river while Iona asks for corroboration.', 'elias nessa thorne iona'),
    (4, 'Lanterns beneath the quay', 'Sable and Ada hide Rowan. Wren’s signal log leads Pip and Oren to a locked quarantine ward beneath the warehouse.', 'sable ada rowan wren pip oren'),
    (5, 'The ledger revealed', 'Rowan’s original ledger implicates Ash Trading and Voss. Mira breaks with Seraphine; Iona prepares publication and Tamsin secures evidence.', 'mira seraphine rowan iona tamsin garrick'),
    (6, 'The blockade', 'Voss seals the harbor and issues warrants. Bram calls a strike; Thorne temporarily cuts ties with Sable to protect the investigation.', 'garrick bram thorne sable dorian'),
    (7, 'A price for testimony', 'Corin admits signing the debt agreement and agrees to testify. Nessa finds Elias alive in the ward; Ada shelters them.', 'corin elias nessa ada liora'),
    (8, 'Storm at the floodgates', 'The storm threatens the ward. Oren repairs the alarm, Wren signals safe passage, and Thorne renews cooperation with Sable for the rescue.', 'oren wren thorne sable pip liora'),
    (9, 'The public hearing', 'Iona publishes the verified documents. Elias and Corin testify; Dorian opens the hearing and Tamsin detains Voss.', 'iona elias corin dorian tamsin garrick'),
    (10, 'A harbor rebuilt', 'The council funds clean medicine and worker inspections. Seraphine offers restitution, but Mira’s distrust remains. New partnerships rebuild the docks.', 'mira seraphine bram dorian liora nessa'),
)

# Source, target, type, notes, shared?, inverse, optional starting chapter.
CONNECTIONS = (
    ('nessa','elias','Family','A daughter searches for her missing father.',True,'',None),
    ('mira','rowan','Family','Siblings separated by Rowan’s guilt.',True,'',None),
    ('seraphine','corin','Family','Siblings disagree about the cost of protecting the company.',True,'',None),
    ('oren','pip','Mentor','Oren taught Pip to build mechanisms safely.',False,'Apprentice',None),
    ('thorne','tamsin','Commander','Tamsin handles the evidence under Thorne’s command.',False,'Lieutenant',None),
    ('garrick','rowan','Blackmailer','Voss threatens to expose Rowan’s forged manifests.',False,'Victim',None),
    ('garrick','corin','Creditor','Charity loans conceal coercive terms.',False,'Debtor',None),
    ('seraphine','garrick','Business partner','Customs favors keep cargo moving.',True,'',None),
    ('mira','liora','Colleague','The healer and physician compare symptoms.',True,'',None),
    ('bram','rowan','Coworker','They share warehouse shifts and safety concerns.',True,'',None),
    ('sable','ada','Friend','Ada reserves a cellar room for Sable’s crew.',True,'',None),
    ('wren','oren','Colleague','They maintain the harbor warning system.',True,'',None),
    ('iona','elias','Research partner','Documents require both archival and journalistic checks.',True,'',None),
    ('dorian','garrick','Political ally','The speaker initially trusts his customs magistrate.',True,'',None),
    ('bram','seraphine','Rival','Bram challenges unsafe contracts.',False,'',None),
    ('seraphine','bram','Employer','Company contracts pay the warehouse crews.',False,'Contractor',None),
    ('corin','liora','Patron','Corin privately funds the ward.',False,'Beneficiary',None),
    ('pip','wren','Friend','Pip delivers books to the lonely lighthouse.',True,'',None),
    ('nessa','sable','Rival','Their boats compete for river traffic.',True,'',None),
    ('ada','nessa','Friend','Nessa brings stranded travelers to the inn.',True,'',None),
    ('tamsin','garrick','Investigator','Tamsin tests the authenticity of the warrants.',False,'Subject',5),
    ('iona','rowan','Reporter','Rowan becomes a named source after verification.',False,'Source',5),
    ('ada','rowan','Protector','Ada hides Rowan from the customs patrol.',False,'Ward',4),
    ('sable','rowan','Rescuer','Sable carries Rowan out of the warehouse tunnels.',False,'Survivor',4),
    ('mira','nessa','Ally','The search for Elias joins their investigations.',True,'',3),
    ('thorne','sable','Ally','A fragile cooperation survives a later interruption.',True,'',4),
    ('oren','liora','Supplier','Oren repairs medical instruments.',False,'Customer',None),
    ('wren','garrick','Witness','Wren’s logs contradict customs arrival records.',False,'Subject',4),
    ('elias','garrick','Witness','Elias identifies the counterfeit seal at the hearing.',False,'Subject',9),
    ('corin','garrick','Witness','Corin admits the debt scheme under oath.',False,'Subject',9),
    ('dorian','iona','Rival','Dorian objects to publication before the hearing.',False,'',5),
    ('tamsin','iona','Ally','They agree how to protect witnesses and evidence.',True,'',5),
    ('bram','nessa','Ally','The ferry carries food during the strike.',True,'',6),
    ('ada','liora','Supplier','The inn feeds patients during the blockade.',False,'Customer',6),
    ('mira','corin','Distrust','Mira doubts Corin’s excuses about the loan.',False,'',5),
    ('pip','rowan','Courier','Pip carries the copied ledger to Mira.',False,'Client',1),
    ('wren','sable','Navigator','Lighthouse signals guide the rescue boat.',False,'Captain',8),
    ('oren','bram','Ally','Workers help repair the flood alarm.',True,'',8),
    ('tamsin','garrick','Captor','The hearing authorizes detention.',False,'Prisoner',9),
    ('dorian','bram','Negotiator','They negotiate independent dock inspections.',True,'',10),
    ('nessa','liora','Volunteer','Nessa ferries patients to follow-up care.',False,'Coordinator',10),
    ('seraphine','liora','Donor','Restitution buys an audited supply of clean medicine.',False,'Recipient',10),
    ('iona','mira','Friend','Sharing the investigation creates a lasting friendship.',True,'',10),
)
